### ISSUE TITLE
example for using own ldapconnection

### ISSUE THREAD

**Issue by v2kiran** [madhatter22/LinqToLdap#11]
Hi 
is is possible to use a custom `System.DirectoryServices.Protocols.Ldapconnection`  with ldapconfiguration ?
if yes could you post an example of how we may use it.

**Comment by madhatter22** [comment]
You need to implement a custom LdapConnectionFactory and register it with the configuration method ConfigureCustomFactory.

**Comment by madhatter22** [comment]
See [LdapConnectionFactory](https://github.com/madhatter22/LinqToLdap/blob/master/LinqToLdap/LdapConnectionFactory.cs) for an example of implementing your own connection factory. Call config.ConfigureCustomFactory(your instance) to configure it.

**Comment by v2kiran** [comment]
thanks
