### ISSUE TITLE
Any planned release date for 4.1.0?

### ISSUE THREAD

**Issue by thomaswurtz** [madhatter22/LinqToLdap#12]
Hi,

I noticed that you have started some work on a 4.1.0 release a while back. Looks very interesting.
Do you have any plan for when to release a stable version of that? :) 

Or if you would like to share what needs to be completed for it to qualify as a non preview in your point of view?

Thanks,
//Thomas

**Comment by madhatter22** [comment]
Yes, I'm looking at releasing it within the next couple of weeks.

**Comment by madhatter22** [comment]
Skipping over 4.1 and going to 5.0. Planning to release it sometime this week. Closed the last task.
