### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by ravensorb** [madhatter22/LinqToLdap#3]
Are there any plans of moving over the docs from codeplex now that it is shutting down?

**Comment by madhatter22** [comment]
Yes, I will finish porting over the code and documentation this month.

**Comment by ravensorb** [comment]
Just checking in on this -- I am using your library in a number of apps and would be bummed if the code disappeared with codeplex shuts down :)

**Comment by madhatter22** [comment]
code has been migrated.

**Comment by monodop** [comment]
According to the [msdn blog post](https://aka.ms/codeplex-announcement), codeplex should have shut down dec 15, 2017. Still not down, but could be any day

**Comment by madhatter22** [comment]
Documentation has been migrated
