### ISSUE TITLE
Version 4 Nuget not adding LinqToLdap.Contrib

### ISSUE THREAD

**Issue by ssteiner** [madhatter22/LinqToLdap#5]
After experimenting with my own builds I wanted to add the nuget variety to my project again - and I noted that if I add the 4.0.0 package, it only adds LinqToLdap to my csproj. If I add 3.3.2 first, I get both LinqToLdap and LinqToLdap.Control and thus the async extensions, and if I then update to 4.0.0 the Contrib library remains. So I think something is wrong with the 4.0.0 nuget.

Also, the version number does not seem to have been updated.. it still says 3.3.2.0.

**Comment by madhatter22** [comment]
I'm getting rid of Contrib in favor of an Async namespace for .Net 4.5 and .Net Standard going forward.
