### ISSUE TITLE
.Net Core

### ISSUE THREAD

**Issue by cwistedt** [madhatter22/LinqToLdap#7]
Hello,

I am just checking if porting linq2ldap to .Net Core is on the roadmap?

**Comment by cdibbs** [comment]
Hello @madhatter22! Hey we were wondering the same. Looks like there is a .NETStandard fork of your library. Any chance of that being pulled in/made official? Thanks!

**Comment by witheej** [comment]
@cdibbs It looks like there is a .NETStandard version that was published to NuGet on May 31, 2018
