### ISSUE TITLE
Unexpected exception

### ISSUE THREAD

**Issue by p1mike** [madhatter22/LinqToLdap#8]
I'm using LinqToLdap in an old asp.net Application (Not MVC, but .net Framework 4). After undefined period of time the AppPool crashes with an System.ArgumentNullException in Application Log. This happens without any user action:

Exception: System.ArgumentNullException
Message: Der Wert darf nicht NULL sein.
StackTrace:    bei System.Threading.Monitor.Enter(Object obj)
   bei LinqToLdap.PooledLdapConnectionFactory.ReleaseConnection(LdapConnection connection)
   bei LinqToLdap.DirectoryContext.Dispose(Boolean disposing)
   bei LinqToLdap.DirectoryContext.Finalize()

**Comment by madhatter22** [comment]
Fixed in net-standard branch.
